site_name: CPSC 128
site_description: Yukon University > CPSC 128 Object-oriented Programming 1
site_author: Tim Topper and Kate Chatfield-Reed
site_url: https://ttopper.github.io/CPSC128
repo_url: https://github.com/ttopper/CPSC128
edit_uri: edit/main/docs/

copyright:
  This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 Unported License</a>.

watch:
- basic_theme
# It didn't seem to watch this automatically ?! so I added it here explicitly.

theme: 
  name: null
  custom_dir: 'basic_theme/'
  highlightjs: true
  hljs_languages:
      - plaintext
      - python
  # name: readthedocs
  #   prev_next_buttons_location: bottom
# theme: gitbook
# theme: windmill


extra_css: 
  - css/extra.css
#  - css/normalize.css
# This is what the documentation at https://www.mkdocs.org/user-guide/configuration/#extra_css says to do, but it's not working...
# WARNING  -  [08:13:53] "GET /css/normalize.css HTTP/1.1" code 404
# Next going to follow the documentation at https://www.mkdocs.org/dev-guide/themes/#theme-files
# "There are various files which a theme treats special in some way. Any other files are simply copied from the theme directory to the same path in the site_dir when the site it built. For example image and CSS files have no special significance and are copied as-is."
# Currently: Have normalize.css living in both docs/css and basic_theme/css

#extra_javascript:
#  - js/menu.js

# Python-Markdown extensions, see https://python-markdown.github.io/extensions/
markdown_extensions:
  # - smarty # Enter Unicode characters!
  - abbr
  - attr_list
  - def_list
  - fenced_code
  - footnotes
  - tables
  - admonition
#  - codehilite
  - sane_lists

plugins:
  - search
#  - img2fig # Did not work for me :-(
  - mermaid2: # Ugly diagrams! Replace with better ones in final version.
      arguments:
        version: 8.6.4
        securityLevel: 'loose'
