mv M01_Introduction/001-big-picture-1-computer-science.md M01_Introduction/01-big-picture-1-computer-science.md
mv M01_Introduction/002-big-picture-2-computers-and-programs.md M01_Introduction/02-big-picture-2-computers-and-programs.md
mv M01_Introduction/003-big-picture-3-programming.md M01_Introduction/03-big-picture-3-programming.md
mv M01_Introduction/004-the-world-of-the-computer-six-key-programming-concepts.md M01_Introduction/04-the-world-of-the-computer-six-key-programming-concepts.md
mv M01_Introduction/005-operation-1-input.md M01_Introduction/05-operation-1-input.md
mv M01_Introduction/006-operation-2-processing.md M01_Introduction/06-operation-2-processing.md
mv M01_Introduction/007-operation-3-output.md M01_Introduction/07-operation-3-output.md
mv M01_Introduction/008-control-structures.md M01_Introduction/08-control-structures.md
mv M01_Introduction/009-operation-4-sequential-execution.md M01_Introduction/09-operation-4-sequential-execution.md
mv M01_Introduction/010-operation-5-selection.md M01_Introduction/10-operation-5-selection.md
mv M01_Introduction/011-operation-6-repetition.md M01_Introduction/11-operation-6-repetition.md
mv M01_Introduction/012-bonus-operation-modularity.md M01_Introduction/12-bonus-operation-modularity.md
mv M01_Introduction/013-summary.md M01_Introduction/13-summary.md
mv M01_Introduction/014-using-the-python-shell.md M01_Introduction/14-using-the-python-shell.md
mv M02_SIPO/001-recall-programming-is....md M02_SIPO/01-recall-programming-is....md
mv M02_SIPO/002-the-problem.md M02_SIPO/02-the-problem.md
mv M02_SIPO/003-do-the-problem-by-hand.md M02_SIPO/03-do-the-problem-by-hand.md
mv M02_SIPO/004-translate-the-algorithm-into-python.md M02_SIPO/04-translate-the-algorithm-into-python.md
mv M02_SIPO/005-enter-run-and-test-the-program.md M02_SIPO/05-enter-run-and-test-the-program.md
mv M02_SIPO/006-naming-values.md M02_SIPO/06-naming-values.md
mv M02_SIPO/007-what-will-it-look-like-onscreen.md M02_SIPO/07-what-will-it-look-like-onscreen.md
mv M02_SIPO/008-documentation.md M02_SIPO/08-documentation.md
mv M02_SIPO/009-our-second-program-same-as-the-first-only-backwards.md M02_SIPO/09-our-second-program-same-as-the-first-only-backwards.md
mv M02_SIPO/010-our-third-program-dhms2s.py.md M02_SIPO/10-our-third-program-dhms2s.py.md
mv M02_SIPO/011-sipo-summary.md M02_SIPO/11-sipo-summary.md
mv M02_SIPO/012-packaging-quantities.md M02_SIPO/12-packaging-quantities.md
mv M02_SIPO/013-modulo-a-sixth-arithmetic-operator.md M02_SIPO/13-modulo-a-sixth-arithmetic-operator.md
mv M02_SIPO/014-symbolic-constants.md M02_SIPO/14-symbolic-constants.md
mv M02_SIPO/015-intermission-summary-so-far.md M02_SIPO/15-intermission-summary-so-far.md
mv M02_SIPO/016-object-types-1-ints-and-floats.md M02_SIPO/16-object-types-1-ints-and-floats.md
mv M02_SIPO/017-example-calculating-tree-radius.md M02_SIPO/17-example-calculating-tree-radius.md
mv M02_SIPO/018-example-value-of-your-change.md M02_SIPO/18-example-value-of-your-change.md
mv M02_SIPO/019-example-making-change.md M02_SIPO/19-example-making-change.md
mv M02_SIPO/020-pythonic-details.md M02_SIPO/20-pythonic-details.md
mv M02_SIPO/021-triple-quoted-strings.md M02_SIPO/21-triple-quoted-strings.md
mv M02_SIPO/022-the-continuation-character.md M02_SIPO/22-the-continuation-character.md
mv M02_SIPO/023-the-done-trick.md M02_SIPO/23-the-done-trick.md
mv M02_SIPO/024-output-formatting.md M02_SIPO/24-output-formatting.md
mv M03_Selection/001-if-a-simple-artificial-example.md M03_Selection/01-if-a-simple-artificial-example.md
mv M03_Selection/002-correcting-an-oversight.md M03_Selection/02-correcting-an-oversight.md
mv M03_Selection/003-if-syntax-in-detail.md M03_Selection/03-if-syntax-in-detail.md
mv M03_Selection/004-relational-expressions.md M03_Selection/04-relational-expressions.md
mv M03_Selection/005-compound-statements-and-indentation.md M03_Selection/05-compound-statements-and-indentation.md
mv M03_Selection/006-example-one-program-to-convert-f-to-c-or-c-to-f.md M03_Selection/06-example-one-program-to-convert-f-to-c-or-c-to-f.md
mv M03_Selection/007-the-problem.md M03_Selection/07-the-problem.md
mv M03_Selection/008-version-1.md M03_Selection/08-version-1.md
mv M03_Selection/009-version-2.md M03_Selection/09-version-2.md
mv M03_Selection/010-testing-selection.md M03_Selection/10-testing-selection.md
mv M03_Selection/011-performance-analysis.md M03_Selection/11-performance-analysis.md
mv M03_Selection/012-a-final-very-small-example-absolute-value.md M03_Selection/12-a-final-very-small-example-absolute-value.md
mv M03_Selection/013-summary-selection-using-if.md M03_Selection/13-summary-selection-using-if.md
mv M03_Selection/014-gazinta-as-in-2-gazinta-8-but-3-doesnt.md M03_Selection/14-gazinta-as-in-2-gazinta-8-but-3-doesnt.md
mv M03_Selection/015-ode-to-pythagoras.md M03_Selection/15-ode-to-pythagoras.md
mv M03_Selection/016-utility-bills.md M03_Selection/16-utility-bills.md
mv M03_Selection/017-beaufort-scale.md M03_Selection/17-beaufort-scale.md
mv M04_Repetition/001-week-4-overview.md M04_Repetition/01-week-4-overview.md
mv M04_Repetition/002-the-idea-go-back-up-and-repeat-some-code.md M04_Repetition/02-the-idea-go-back-up-and-repeat-some-code.md
mv M04_Repetition/003-the-flowchart.md M04_Repetition/03-the-flowchart.md
mv M04_Repetition/004-the-syntax.md M04_Repetition/04-the-syntax.md
mv M04_Repetition/005-hihihi.md M04_Repetition/05-hihihi.md
mv M04_Repetition/006-infinite-loops.md M04_Repetition/06-infinite-loops.md
mv M04_Repetition/008-validating-input.md M04_Repetition/08-validating-input.md
mv M04_Repetition/010-repeating-a-program-without-restarting-it.md M04_Repetition/10-repeating-a-program-without-restarting-it.md
mv M04_Repetition/012-problem-repeating-calculations.md M04_Repetition/12-problem-repeating-calculations.md
mv M04_Repetition/013-example-find-the-average.md M04_Repetition/13-example-find-the-average.md
mv M04_Repetition/014-sentinel-controlled-input.md M04_Repetition/14-sentinel-controlled-input.md
mv M04_Repetition/015-problem-the-guessing-game.md M04_Repetition/15-problem-the-guessing-game.md
mv M04_Repetition/016-aside-getting-random-numbers.md M04_Repetition/16-aside-getting-random-numbers.md
mv M04_Repetition/017-solution-the-guessing-game.md M04_Repetition/17-solution-the-guessing-game.md
mv M04_Repetition/018-a-puzzle-what-output-does-this-produce.md M04_Repetition/18-a-puzzle-what-output-does-this-produce.md
mv M04_Repetition/019-nesting-loops.md M04_Repetition/19-nesting-loops.md
mv M04_Repetition/020-pythons-other-repetition-structure-for-loops.md M04_Repetition/20-pythons-other-repetition-structure-for-loops.md
mv M04_Repetition/021-completely-artificial-example-revisited-using-for.md M04_Repetition/21-completely-artificial-example-revisited-using-for.md
mv M04_Repetition/022-for-vs-while.md M04_Repetition/22-for-vs-while.md
mv M04_Repetition/023-f2c-revisited-fahrenheit-to-celsius-conversion-table-using-for.md M04_Repetition/23-f2c-revisited-fahrenheit-to-celsius-conversion-table-using-for.md
mv M04_Repetition/024-nesting-for-loops.md M04_Repetition/24-nesting-for-loops.md
mv M04_Repetition/025-example-draw-a-square.md M04_Repetition/25-example-draw-a-square.md
mv M04_Repetition/026-module-4-summary.md M04_Repetition/26-module-4-summary.md
mv M04_Repetition/027-brute-force.md M04_Repetition/27-brute-force.md
mv M04_Repetition/028-simulation.md M04_Repetition/28-simulation.md
mv M04_Repetition/029-problem-what-are-the-chances-four-children-all-girls.md M04_Repetition/29-problem-what-are-the-chances-four-children-all-girls.md
mv M04_Repetition/030-duelling-incompetents.md M04_Repetition/30-duelling-incompetents.md
mv M04_Repetition/031-factors.md M04_Repetition/31-factors.md
mv M04_Repetition/032-cryptarithms.md M04_Repetition/32-cryptarithms.md
mv M04_Repetition/033-python-formatting-guidelines.md M04_Repetition/33-python-formatting-guidelines.md
mv M04_Repetition/034-a-list-creating-function-range.md M04_Repetition/34-a-list-creating-function-range.md
mv M04_Repetition/035-timing-programs.md M04_Repetition/35-timing-programs.md
mv M05_Lists_and_Strings/001-object-based-programming.md M05_Lists_and_Strings/01-object-based-programming.md
mv M05_Lists_and_Strings/002-sequence-types.md M05_Lists_and_Strings/02-sequence-types.md
mv M05_Lists_and_Strings/003-what-can-you-do-with-a-list.md M05_Lists_and_Strings/03-what-can-you-do-with-a-list.md
mv M05_Lists_and_Strings/004-what-can-you-do-with-a-string.md M05_Lists_and_Strings/04-what-can-you-do-with-a-string.md
mv M05_Lists_and_Strings/005-example-cd-shuffle.md M05_Lists_and_Strings/05-example-cd-shuffle.md
mv M05_Lists_and_Strings/006-dice-odds.md M05_Lists_and_Strings/06-dice-odds.md
mv M05_Lists_and_Strings/007-bar-graphs.md M05_Lists_and_Strings/07-bar-graphs.md
mv M05_Lists_and_Strings/008-representing-playing-cards.md M05_Lists_and_Strings/08-representing-playing-cards.md
mv M05_Lists_and_Strings/009-poker-hands.md M05_Lists_and_Strings/09-poker-hands.md
mv M05_Lists_and_Strings/010-playing-cards-an-alternative-representation.md M05_Lists_and_Strings/10-playing-cards-an-alternative-representation.md
mv M05_Lists_and_Strings/011-what-is-this-x-o-o-x-o-x.md M05_Lists_and_Strings/11-what-is-this-x-o-o-x-o-x.md
mv M05_Lists_and_Strings/012-palindrome.md M05_Lists_and_Strings/12-palindrome.md
mv M05_Lists_and_Strings/013-built-in-type-conversions.md M05_Lists_and_Strings/13-built-in-type-conversions.md
mv M05_Lists_and_Strings/014-the-map-function.md M05_Lists_and_Strings/14-the-map-function.md
mv M05_Lists_and_Strings/015-tuples.md M05_Lists_and_Strings/15-tuples.md
mv M06_Functions/001-modularization.md M06_Functions/01-modularization.md
mv M06_Functions/002-functions.md M06_Functions/02-functions.md
mv M06_Functions/003-writing-functions-is_even.md M06_Functions/03-writing-functions-is_even.md
mv M06_Functions/004-writing-functions-syntax-summary.md M06_Functions/04-writing-functions-syntax-summary.md
mv M06_Functions/005-is_odd.md M06_Functions/05-is_odd.md
mv M06_Functions/006-example-dice_roll.md M06_Functions/06-example-dice_roll.md
mv M06_Functions/007-default-arguments.md M06_Functions/07-default-arguments.md
mv M06_Functions/008-playing-card-functions-1.md M06_Functions/08-playing-card-functions-1.md
mv M06_Functions/009-reusing-functions.md M06_Functions/09-reusing-functions.md
mv M06_Functions/010-modules.md M06_Functions/10-modules.md
mv M06_Functions/011-documenting-modules-and-functions.md M06_Functions/11-documenting-modules-and-functions.md
mv M06_Functions/012-summary-module-layout.md M06_Functions/12-summary-module-layout.md
mv M06_Functions/013-example-playing-card-functions-2.md M06_Functions/13-example-playing-card-functions-2.md
mv M06_Functions/014-refining-import.md M06_Functions/14-refining-import.md
mv M06_Functions/015-scope.md M06_Functions/15-scope.md
mv M06_Functions/016-the-perils-of-mutability.md M06_Functions/16-the-perils-of-mutability.md
mv M06_Functions/017-reference-semantics.md M06_Functions/17-reference-semantics.md
mv M06_Functions/018-using-versus-changing-a-list.md M06_Functions/18-using-versus-changing-a-list.md
mv M06_Functions/019-copying-a-list.md M06_Functions/19-copying-a-list.md
mv M06_Functions/020-list-comprehensions.md M06_Functions/20-list-comprehensions.md
mv M06_Functions/021-what-are-these-pyc-files.md M06_Functions/21-what-are-these-pyc-files.md
mv M06_Functions/022-finding-the-standard-library-modules.md M06_Functions/22-finding-the-standard-library-modules.md
mv M07_Dictionaries/001-dictionaries.md M07_Dictionaries/01-dictionaries.md
mv M07_Dictionaries/002-dictionary-derivation.md M07_Dictionaries/02-dictionary-derivation.md
mv M07_Dictionaries/003-what-can-you-do-with-a-dictionary.md M07_Dictionaries/03-what-can-you-do-with-a-dictionary.md
mv M07_Dictionaries/004-example-word-frequencies.md M07_Dictionaries/04-example-word-frequencies.md
mv M07_Dictionaries/005-example-scrabble-scoring.md M07_Dictionaries/05-example-scrabble-scoring.md
mv M07_Dictionaries/006-example-book-database.md M07_Dictionaries/06-example-book-database.md
mv M07_Dictionaries/007-example-a-list-of-dictionaries.md M07_Dictionaries/07-example-a-list-of-dictionaries.md
mv M08_Persistence/001-persistence.md M08_Persistence/01-persistence.md
mv M08_Persistence/003-text-versus-binary-files.md M08_Persistence/03-text-versus-binary-files.md
mv M08_Persistence/004-reading-from-text-files.md M08_Persistence/04-reading-from-text-files.md
mv M08_Persistence/005-example-searching-log-files.md M08_Persistence/05-example-searching-log-files.md
mv M08_Persistence/006-important-note-files-are-sequential.md M08_Persistence/06-important-note-files-are-sequential.md
mv M08_Persistence/007-is-there-more.md M08_Persistence/07-is-there-more.md
mv M08_Persistence/008-writing-to-text-files.md M08_Persistence/08-writing-to-text-files.md
mv M08_Persistence/009-appending-to-files.md M08_Persistence/09-appending-to-files.md
mv M08_Persistence/010-reading-numeric-data.md M08_Persistence/10-reading-numeric-data.md
mv M08_Persistence/011-designing-file-formats.md M08_Persistence/11-designing-file-formats.md
mv M08_Persistence/012-pickling.md M08_Persistence/12-pickling.md
mv M08_Persistence/013-shelves.md M08_Persistence/13-shelves.md
mv M08_Persistence/014-a-controller-for-our-database.md M08_Persistence/14-a-controller-for-our-database.md
mv M08_Persistence/015-the-main-event-loop.md M08_Persistence/15-the-main-event-loop.md
mv M09_OOP1_Encapsulation/001-object-oriented-programming.md M09_OOP1_Encapsulation/01-object-oriented-programming.md
mv M09_OOP1_Encapsulation/002-encapsulation.md M09_OOP1_Encapsulation/02-encapsulation.md
mv M09_OOP1_Encapsulation/003-inheritance.md M09_OOP1_Encapsulation/03-inheritance.md
mv M09_OOP1_Encapsulation/004-polymorphism.md M09_OOP1_Encapsulation/04-polymorphism.md
mv M09_OOP1_Encapsulation/005-the-plan-for-the-next-three-modules.md M09_OOP1_Encapsulation/05-the-plan-for-the-next-three-modules.md
mv M09_OOP1_Encapsulation/006-a-small-example-a-dice-class.md M09_OOP1_Encapsulation/06-a-small-example-a-dice-class.md
mv M09_OOP1_Encapsulation/007-python-oop-syntax.md M09_OOP1_Encapsulation/07-python-oop-syntax.md
mv M09_OOP1_Encapsulation/008-playing-card-classes-the-specification.md M09_OOP1_Encapsulation/08-playing-card-classes-the-specification.md
mv M09_OOP1_Encapsulation/009-identifying-the-necessary-classes.md M09_OOP1_Encapsulation/09-identifying-the-necessary-classes.md
mv M09_OOP1_Encapsulation/010-identifying-the-classes-methods.md M09_OOP1_Encapsulation/10-identifying-the-classes-methods.md
mv M09_OOP1_Encapsulation/011-program-skeleton-1.md M09_OOP1_Encapsulation/11-program-skeleton-1.md
mv M09_OOP1_Encapsulation/012-an-invisible-method-a-polymorphic-aside.md M09_OOP1_Encapsulation/12-an-invisible-method-a-polymorphic-aside.md
mv M09_OOP1_Encapsulation/013-program-skeleton-2.md M09_OOP1_Encapsulation/13-program-skeleton-2.md
mv M09_OOP1_Encapsulation/014-an-invisible-class-too.md M09_OOP1_Encapsulation/14-an-invisible-class-too.md
mv M09_OOP1_Encapsulation/015-deck-methods.md M09_OOP1_Encapsulation/15-deck-methods.md
mv M09_OOP1_Encapsulation/016-hand-methods.md M09_OOP1_Encapsulation/16-hand-methods.md
mv M09_OOP1_Encapsulation/017-card-methods.md M09_OOP1_Encapsulation/17-card-methods.md
mv M09_OOP1_Encapsulation/018-putting-all-the-pieces-together.md M09_OOP1_Encapsulation/18-putting-all-the-pieces-together.md
mv M09_OOP1_Encapsulation/019-running-the-whole-thing.md M09_OOP1_Encapsulation/19-running-the-whole-thing.md
mv M09_OOP1_Encapsulation/020-programming-observation.md M09_OOP1_Encapsulation/20-programming-observation.md
mv M10_OOD/001-object-oriented-design-ood.md M10_OOD/01-object-oriented-design-ood.md
mv M10_OOD/002-preamble-to-hunt-the-wumpus.md M10_OOD/02-preamble-to-hunt-the-wumpus.md
mv M10_OOD/003-about-hunt-the-wumpus.md M10_OOD/03-about-hunt-the-wumpus.md
mv M10_OOD/004-oo-analysis.md M10_OOD/04-oo-analysis.md
mv M10_OOD/005-object-attributes-and-methods.md M10_OOD/05-object-attributes-and-methods.md
mv M10_OOD/006-the-cave-system-objects.md M10_OOD/06-the-cave-system-objects.md
mv M10_OOD/007-main-routine-pseudocode.md M10_OOD/07-main-routine-pseudocode.md
mv M10_OOD/008-class-cave_system.md M10_OOD/08-class-cave_system.md
mv M10_OOD/009-aside-iterative-design.md M10_OOD/09-aside-iterative-design.md
mv M10_OOD/010-class-room.md M10_OOD/10-class-room.md
mv M10_OOD/011-class-pit.md M10_OOD/11-class-pit.md
mv M10_OOD/012-class-bat.md M10_OOD/12-class-bat.md
mv M10_OOD/013-class-wumpus.md M10_OOD/13-class-wumpus.md
mv M10_OOD/014-class-player.md M10_OOD/14-class-player.md
mv M10_OOD/015-putting-the-pieces-together.md M10_OOD/15-putting-the-pieces-together.md
mv M10_OOD/016-new-code-initializing-the-bats.md M10_OOD/16-new-code-initializing-the-bats.md
mv M10_OOD/017-new-code-pointing-to-a-missing-class-shoot-and-arrows.md M10_OOD/17-new-code-pointing-to-a-missing-class-shoot-and-arrows.md
mv M10_OOD/018-new-code-show_cheats.md M10_OOD/18-new-code-show_cheats.md
mv M10_OOD/019-new-code-display-status-and-warnings.md M10_OOD/19-new-code-display-status-and-warnings.md
mv M10_OOD/020-memory-diagram.md M10_OOD/20-memory-diagram.md
mv M10_OOD/021-bug-fixing-mostly-snatch.md M10_OOD/21-bug-fixing-mostly-snatch.md
mv M10_OOD/022-aside-data-structure-maintenance.md M10_OOD/22-aside-data-structure-maintenance.md
mv M10_OOD/023-two-more-small-problems.md M10_OOD/23-two-more-small-problems.md
mv M10_OOD/024-howd-we-do.md M10_OOD/24-howd-we-do.md
mv M11_OOP2_Polymorphism_and_Inheritance/001-inheritance-and-polymorphism.md M11_OOP2_Polymorphism_and_Inheritance/01-inheritance-and-polymorphism.md
mv M11_OOP2_Polymorphism_and_Inheritance/002-inheritance-example-playing-cards.md M11_OOP2_Polymorphism_and_Inheritance/02-inheritance-example-playing-cards.md
mv M11_OOP2_Polymorphism_and_Inheritance/003-class-cardcollection.md M11_OOP2_Polymorphism_and_Inheritance/03-class-cardcollection.md
mv M11_OOP2_Polymorphism_and_Inheritance/004-class-deck.md M11_OOP2_Polymorphism_and_Inheritance/04-class-deck.md
mv M11_OOP2_Polymorphism_and_Inheritance/005-class-hand.md M11_OOP2_Polymorphism_and_Inheritance/05-class-hand.md
mv M11_OOP2_Polymorphism_and_Inheritance/006-putting-the-pieces-together.md M11_OOP2_Polymorphism_and_Inheritance/06-putting-the-pieces-together.md
mv M11_OOP2_Polymorphism_and_Inheritance/007-aside-refactoring.md M11_OOP2_Polymorphism_and_Inheritance/07-aside-refactoring.md
mv M11_OOP2_Polymorphism_and_Inheritance/008-polymorphism.md M11_OOP2_Polymorphism_and_Inheritance/08-polymorphism.md
mv M11_OOP2_Polymorphism_and_Inheritance/009-example-fractions.md M11_OOP2_Polymorphism_and_Inheritance/09-example-fractions.md
mv M11_OOP2_Polymorphism_and_Inheritance/010-reverse-engineering.md M11_OOP2_Polymorphism_and_Inheritance/10-reverse-engineering.md
mv M11_OOP2_Polymorphism_and_Inheritance/011-class-fraction.md M11_OOP2_Polymorphism_and_Inheritance/11-class-fraction.md
mv M11_OOP2_Polymorphism_and_Inheritance/012-example-playing-cards.md M11_OOP2_Polymorphism_and_Inheritance/12-example-playing-cards.md
mv M11_OOP2_Polymorphism_and_Inheritance/013-a-subtle-point-semantics.md M11_OOP2_Polymorphism_and_Inheritance/13-a-subtle-point-semantics.md
mv M11_OOP2_Polymorphism_and_Inheritance/014-conclusion-adding-types.md M11_OOP2_Polymorphism_and_Inheritance/14-conclusion-adding-types.md
mv M12_Testing_and_Documentation/001-uml-and-testing-with-doctest.md M12_Testing_and_Documentation/01-uml-and-testing-with-doctest.md
mv M12_Testing_and_Documentation/002-unified-modelling-language-uml.md M12_Testing_and_Documentation/02-unified-modelling-language-uml.md
mv M12_Testing_and_Documentation/003-aside-is-a-versus-has-a.md M12_Testing_and_Documentation/03-aside-is-a-versus-has-a.md
mv M12_Testing_and_Documentation/004-uml-class-diagram-visual-syntax.md M12_Testing_and_Documentation/04-uml-class-diagram-visual-syntax.md
mv M12_Testing_and_Documentation/005-example-playing-card-classes.md M12_Testing_and_Documentation/05-example-playing-card-classes.md
mv M12_Testing_and_Documentation/006-testing-with-doctest.md M12_Testing_and_Documentation/06-testing-with-doctest.md
